default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['MYSQL_LOGIN_NAME'] %>
  password: <%= ENV['MYSQL_LOGIN_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  database: uber_eats_like_production

development:
  <<: *default
  database: uber_eats_like_development
